### ISSUE TITLE
Extension suddenly doesn't work

### ISSUE THREAD

**Issue by keith-ken** [jerry1100/messenger-dark-theme#10]
I've been using the extension for a long time, and oh boy, my eyes had a great time. Yesterday, my Messenger suddenly reloaded, and the extension was deactivated. Gone are the days my eyes are pleased. I tried restarting the system, removing and redownloading the extension. Nothing worked. I'm on Microsoft Edge Desktop.

**Comment by jerry1100** [comment]
Hey Keith,

Can you make sure the extension has access to messenger.com <http://messenger.com/>?

Jerry

**Comment by ddragman** [comment]
![2020-11-23 15_16_06-Window](https://user-images.githubusercontent.com/5765452/99972820-47a55680-2d9f-11eb-9b3d-63e5458f8977.png)
Same issue here. Surprisingly none of the addins does not work in Chrome too. 
I have atteched the image where you can see the extension has access to messenger.

**Comment by keith-ken** [comment]
![Not working](https://user-images.githubusercontent.com/69977010/99979210-d044e680-2de1-11eb-880d-6dba4ccb2d15.png)

It has access to messenger, still doesn't work. Restarting the device or redownloading the extension does not work as well.

**Comment by jerry1100** [comment]
For some reason I can't reproduce it. I tried on both Windows & Mac. Could you provide the following:
1. Operating System:
2. Browser Version:

Another possibility is that messenger updated their web app, but I couldn't figure out how to get the version number of the web app.

**Comment by ddragman** [comment]
My browser is Microsoft Edge Version 86.0.622.48 (Official build) (64-bit) on Windows 10 Enterprise, Version 1909, Build 18363.1198.

There was definitely an update from Messenger, because I got the prompt to reload web page to refresh web app. After the refresh, black theme stopped working. Maybe yours was not updated yet and thas is the reason you can not reproduce it. 

PS: I have tested other similar extensions in Chrome and neither of them works in my case. I gues updated web app is the cause.

**Comment by jerry1100** [comment]
Thanks for the update @ddragman. I'll continue to check until I can get the update as well.

In the meantime, could you try clear the site data?
1. Go to messenger.com
2. Press <kbd>ctrl</kbd><kbd>shift</kbd><kbd>i</kbd>
3. Go to the Application tab and click "Clear site data"

<img width="1459" alt="Screen Shot 2020-11-23 at 7 50 42 AM" src="https://user-images.githubusercontent.com/18181641/99997121-cb8c1e00-2d60-11eb-9ddf-1e3fff81c6d8.png">

**Comment by ddragman** [comment]
I have cleared site data, no change.

**Comment by jerry1100** [comment]
Shucks. I guess we'll just have to wait until I can get on the update.

**Comment by ddragman** [comment]
Will do ;)

**Comment by ddragman** [comment]
@jerry1100 it started woking today, after I had to make a restart because of driver updates.

**Comment by jerry1100** [comment]
Interesting. I'm still unable to update to the new messenger and repro the issue. Perhaps Facebook is doing a slow rollout or just experimenting.

@keith-ken are you still hitting this?

**Comment by ddragman** [comment]
@jerry1100 same issue again on my computer :) Began with the restart, after some driver updates were installed.

**Comment by jerry1100** [comment]
Shucks. Unfortunately I still can't get the update, so I can't repro. We'll just have to wait until Facebook rolls out the update to everyone.

**Comment by paravorheim** [comment]
In the meantime, if you are still looking for a dark mode option, if you have set Facebook to dark mode use https://www.facebook.com/messages to access messages, you can full screen it to avoid most of the Facebook stuff.

**Comment by Ketrimoner** [comment]
I do have the same issue, I tried reinstalling the "Install Chrome Extension" and the dark mode extension as well, but no result whatsoever.

**Comment by jerry1100** [comment]
Just checked and it looks like Facebook rolled out the update to everyone. I'll take a look later today to see if I can update the extension to work with the new version.

**Comment by jerry1100** [comment]
Hey everyone, I just published v1.0 which works with the new messenger. Please give it a try.

If you see any issues, [create a new issue](https://github.com/jerry1100/messenger-dark-theme/issues/new) and I'll jump on it.
