### ISSUE TITLE
Background of menus and settings

### ISSUE THREAD

**Issue by ghost** [jerry1100/messenger-dark-theme#11]
Hello,
is there a chance that you'll also change the color of background of setting list (and other list - conversation settings  and profile menu - the one after you click on your profile pic) to darker one, like everywhere else?
![image](https://user-images.githubusercontent.com/62335743/100747377-4220bf80-33e2-11eb-9eb6-000f4dc4fb8f.png)

**Comment by jerry1100** [comment]
Not planning on it since it'll increase the maintenance cost, and those menus are probably not used that often.

**Comment by ghost** [comment]
Understandable, thanks for the answer.
