### ISSUE TITLE
safari support

### ISSUE THREAD

**Issue by paravorheim** [jerry1100/messenger-dark-theme#12]
Just want you to know that the extension in its current form works perfectly in Safari. Just ran the following command on src folder

`xcrun safari-web-extension-converter`

And then ran on Safari. Unfortunately distribution of Safari Web Extensions requires a developer license

**Comment by jerry1100** [comment]
Awesome, that's good to know. If & when I do get a license, I'll look into porting it there.

That is, unless Facebook adds a native dark mode first :)

**Comment by ADTC** [comment]
If Facebook wanted to add dark mode, they would have done so already. I mean, they literally admit in the help docs that there's no dark mode in the standalone messenger, yet there is one in the embedded messenger in Facebook. I believe they are trying to push everyone to use the embedded one (or the App) by holding off the dark mode in standalone. Dirty tactics! Honestly just waiting for them to kill the standalone Messenger one day (hope it doesn't happen, knock on wood).

**Comment by jerry1100** [comment]
Going to close this since [I'll be deprecating this extension](https://github.com/jerry1100/messenger-dark-theme?tab=readme-ov-file#messenger-dark-theme-deprecated).

Thanks for the support!
