### ISSUE TITLE
White scroll bars on Chrome Linux Mint

### ISSUE THREAD

**Issue by kaielvin** [jerry1100/messenger-dark-theme#13]
The theme looks great, but the scroll bars are white and very flashy in contrast. I'm on Chrome on Linux Mint.

**Comment by jerry1100** [comment]
I should be able to override scrollbar styles on Chrome. Let me give it a crack this weekend.

**Comment by jerry1100** [comment]
I just published v1.1 with the updated scrollbars. Give it a try and let me know what you think!

**Comment by kaielvin** [comment]
Looking great. Thanks a lot. Do you accept Bitcoin donations?

**Comment by jerry1100** [comment]
Haha I appreciate the offer, but I'm okay 😄
