### ISSUE TITLE
Suddenly Not Working

### ISSUE THREAD

**Issue by keith-ken** [jerry1100/messenger-dark-theme#14]
Good day!

The plugin suddenly stopped working. Can I get some assistance?

Thanks!
![image](https://user-images.githubusercontent.com/69977010/125878404-f74ffb47-5604-437e-8af8-fbb82340edc5.png)

**Comment by jerry1100** [comment]
Can you verify that the extension has access to the page? Like you did before:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/18181641/125880248-1f364e73-7600-4126-bb67-559198dc7a8c.png">

If so, it could just be facebook rolling out a new update that breaks the extension's styling. In which case I'll need to wait until I get the rollout as well (I just tried and the extension still works for me).

**Comment by keith-ken** [comment]
> Can you verify that the extension has access to the page? Like you did before:
> <img alt="image" width="528" src="https://user-images.githubusercontent.com/18181641/125880248-1f364e73-7600-4126-bb67-559198dc7a8c.png">
> 
> If so, it could just be facebook rolling out a new update that breaks the extension's styling. In which case I'll need to wait until I get the rollout as well (I just tried and the extension still works for me).

![image](https://user-images.githubusercontent.com/69977010/125882977-9f9e972a-4758-4e58-a4b5-100b226e6dc5.png)

Yes, sir. The settings are correct. I think its the new update

**Comment by keith-ken** [comment]
It's working now. Thank you for the support!

**Comment by jerry1100** [comment]
Since you said it's working, I'm going to close this issue
