### ISSUE TITLE
Incoming message color not correct

### ISSUE THREAD

**Issue by mr-davit** [jerry1100/messenger-dark-theme#15]
![image](https://user-images.githubusercontent.com/77172061/128347208-f2793ff8-2e6b-4fe0-9cf9-e103977b2a66.png)
Incoming message background color is too dark or maybe text color should be white

**Comment by jerry1100** [comment]
Thanks for reporting, taking a look

**Comment by jerry1100** [comment]
Just published v1.2 which fixes this.
