### ISSUE TITLE
Dark Colored Text for Receiving Messages

### ISSUE THREAD

**Issue by Xerolz** [jerry1100/messenger-dark-theme#16]
![image](https://user-images.githubusercontent.com/88566664/128584109-af45331b-c606-447d-b01b-e53cba4dc2e6.png)
![image](https://user-images.githubusercontent.com/88566664/128584125-a97f7c2e-da3b-4682-9b3f-9fd4b4854ff0.png)
![image](https://user-images.githubusercontent.com/88566664/128584148-46880a78-c46c-4588-a510-b0e3fcd3746a.png)

It was white in color and fine just a few days ago...

**Comment by jerry1100** [comment]
Thanks for reporting, taking a look

**Comment by jerry1100** [comment]
Just published v1.2 which fixes this.
