### ISSUE TITLE
Display issue - black text on grey bubbles

### ISSUE THREAD

**Issue by Lutra-Arce** [jerry1100/messenger-dark-theme#17]
As described before, there was probably an update or something today that broke the extension and now the colors are wrong. Looking forward to the fix. Thanks for making this extension, I have been using it as long as I can remember and it has been a godsend for years.

Example:
![image](https://user-images.githubusercontent.com/88830610/129183923-8014f40c-4180-49cd-88f1-302833063e17.png)

**Comment by keith-ken** [comment]
> As described before, there was probably an update or something today that broke the extension and now the colors are wrong. Looking forward to the fix. Thanks for making this extension, I have been using it as long as I can remember and it has been a godsend for years.
> 
> Example:
> ![image](https://user-images.githubusercontent.com/88830610/129183923-8014f40c-4180-49cd-88f1-302833063e17.png)

Good day!

I am also having the same issue.

![image](https://user-images.githubusercontent.com/69977010/129215844-57551345-6c7a-47fc-81cf-61b041de2812.png)

**Comment by jerry1100** [comment]
Are you guys on v1.2? I just released that on Sunday. You can check by going to Chrome's extension page. There's also an update button.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/18181641/129286349-ae228803-58fa-4e9f-8531-1c6e78758bea.png">

**Comment by keith-ken** [comment]
> Are you guys on v1.2? I just released that on Sunday. You can check by going to Chrome's extension page. There's also an update button.
> 
> <img alt="image" width="501" src="https://user-images.githubusercontent.com/18181641/129286349-ae228803-58fa-4e9f-8531-1c6e78758bea.png">

That fixed it. Thanks!

Mine did not update because the update is not available in MS Edge. I just downloaded it from the Chrome store.

Thanks again! Problem resolved

**Comment by Lutra-Arce** [comment]
Switching to the Chrome extension did fix it. It saddens me a bit that the updates on the Edge extension store are not in parity with the Chrome ones, but such is life. Thanks for the solution, problem resolved.

**Comment by jerry1100** [comment]
Yeah, it's too bad. I pushed the update to both stores on Sunday. The Chrome store updated it immediately whereas the Edge store just approved & published it yesterday.

FWIW, you can get the newer version on the Edge store too, as of yesterday.
