### ISSUE TITLE
Dark Scrollbars

### ISSUE THREAD

**Issue by matthew-e-brown** [jerry1100/messenger-dark-theme#19]
While full support for custom CSS scrollbars isn't yet available without some `-webkit` hackery, it appears you can get Windows to render scrollbars in darkmode with the `color-scheme` property.

https://stackoverflow.com/a/66097469/10549827
https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

Are there any plans to implement this? It doesn't seem too complicated; I would gladly make a PR.

**Comment by jerry1100** [comment]
Cool, I didn't know that. Thanks for sharing.

Seems like a small enough change so I can handle it. Appreciate the PR offer though.

Could you post before & after screenshots with this setting? Just add it via dev tools or something.

**Comment by matthew-e-brown** [comment]
Sure. Here's before: 

![image](https://user-images.githubusercontent.com/43387454/144679894-8f3f91f5-e1e8-440d-8fe9-cc4db27a84de.png)

And here's after:

![image](https://user-images.githubusercontent.com/43387454/144679949-eeacd984-2fef-4286-90bd-efc443143f69.png)

The element I stuck it on in this example is just the `<html>` (`:root`). It seems to cascade properly to all children.

**Comment by jerry1100** [comment]
Looks good, will try it out.

**Comment by jerry1100** [comment]
v1.3 is published with dark scrollbars! Thanks for the suggestion, this looks a lot better.

**Comment by matthew-e-brown** [comment]
Awesome! What a fast turnaround, thanks. It looks great 😄
