### ISSUE TITLE
A Few Missed Icons

### ISSUE THREAD

**Issue by Mandrenkov** [jerry1100/messenger-dark-theme#2]
Hello,

It looks like there are a few places where the extension isn't colouring the Messenger icons correctly.  These include:

1. The show (and hide) additional actions button.

![image](https://user-images.githubusercontent.com/5883774/97997476-fbc24b80-1db6-11eb-8390-675f099afc77.png)

2. The hole inside the **Change Theme** preview icon.

![image](https://user-images.githubusercontent.com/5883774/97997818-5c518880-1db7-11eb-9563-82958845d341.png)

3. The **Create new room** button in the Chat panel.

![image](https://user-images.githubusercontent.com/5883774/97997848-68d5e100-1db7-11eb-83cd-5fbf427db723.png)

**Comment by jerry1100** [comment]
Thanks @Mandrenkov for reporting, and including screenshots--they were super helpful.

I submitted a new version (v0.7). Will probably take a few days to get approved and published, but expect to see the changes soon.

![image](https://user-images.githubusercontent.com/18181641/98492812-10e71200-21dd-11eb-9ff8-661ab6a7bbf0.png)
![image](https://user-images.githubusercontent.com/18181641/98492860-31af6780-21dd-11eb-85d5-bc55f92dfa14.png)
![image](https://user-images.githubusercontent.com/18181641/98492874-3a07a280-21dd-11eb-8823-5a14c185e94c.png)
