### ISSUE TITLE
Thumbs-up sign emoji color changed to white

### ISSUE THREAD

**Issue by maxoku** [jerry1100/messenger-dark-theme#20]
The thumbs-up sign emoji that can be quickly inserted to the chat with a button changes it's color to white.
![image](https://user-images.githubusercontent.com/17256400/147251527-ee3c3f4d-d5b3-4713-bfa3-4cd3d5eff4fa.png)
This is how it looks without the add-on:
![image](https://user-images.githubusercontent.com/17256400/147251572-d93b8fb9-3b5c-4211-b1ee-fe7487e855ed.png)
Could you fix that its color wouldn't be changed?

**Comment by jerry1100** [comment]
Thanks for reporting! This is fixed in v1.15 which is now live in the chrome web store.

**Comment by maxoku** [comment]
Nice, thanks.
