### ISSUE TITLE
Some icons have broken

### ISSUE THREAD

**Issue by matthew-e-brown** [jerry1100/messenger-dark-theme#21]
It seems that, recently, Facebook made some changes that stopped the selectors from applying to every icon properly. Some of them are no longer changed to white:

![](https://user-images.githubusercontent.com/43387454/160223380-cf991a58-17b9-43bb-b64d-02b6a5c645e8.png)

![](https://user-images.githubusercontent.com/43387454/160223383-e388b2c0-bc71-42a3-a305-8712a7f6fc30.png)

**Comment by jerry1100** [comment]
Just released v1.6 which fixes these. Thanks for including screenshots, they're really helpful.

<img width="216" alt="Screen Shot 2022-04-13 at 12 31 07 PM" src="https://user-images.githubusercontent.com/18181641/163256715-b1efe8fb-d81f-4861-82f5-32a14936f863.png">

<img width="352" alt="Screen Shot 2022-04-13 at 12 31 14 PM" src="https://user-images.githubusercontent.com/18181641/163256718-b312dbc8-e79b-416b-86be-dc59e743328e.png">
