### ISSUE TITLE
Messenger Dark Lines

### ISSUE THREAD

**Issue by janjan0718** [jerry1100/messenger-dark-theme#23]

**Comment by janjan0718** [comment]
hi! I'm getting weird line while scrolling through messenger. Any way to fix this? Thanks! Keep up the great work!
![image](https://user-images.githubusercontent.com/123434774/214207459-9a844f65-9107-44ce-915e-01ebfd5b1229.png)

**Comment by jerry1100** [comment]
@janjan0718 I can't reproduce. Could you try restarting your computer? If that doesn't work, let me know:
1. the browser you're using
2. if you're on windows or Mac

**Comment by ghost** [comment]
Hi, same problem here in Microsoft Edge while scrolling in Messenger. Restart of computer did not work. 
Win ver: Windows 11 22H2 (OS Build 22621.1194) - latest update, january 23
Microsoft Edge: Version 109.0.1518.70 (Official build) (64-bit)
![fb_dark](https://user-images.githubusercontent.com/123987987/215567745-dc273570-4e59-4edc-ba17-2d27e766cea1.png)

**Comment by jerry1100** [comment]
@crucinal1 does it also repro on Chrome? What does it look like on Edge without the extension (light mode)?

**Comment by ghost** [comment]
> @crucinal1 does it also repro on Chrome? What does it look like on Edge without the extension (light mode)?

tested it and same problem without the extension. already reported a bug to messenger team. thanks

**Comment by jerry1100** [comment]
Thanks for checking. One thing you could try is disabling hardware acceleration in Edge ([instructions](https://www.thewindowsclub.com/enable-or-disable-hardware-acceleration-in-edge)).
