### ISSUE TITLE
Any chance for a JS variant?

### ISSUE THREAD

**Issue by wefalltomorrow** [jerry1100/messenger-dark-theme#24]
Trying to use this lovely theme with Hamsket, which allows JS injection but not SCSS sadly.

**Comment by jerry1100** [comment]
You can inject the [css file here](https://github.com/jerry1100/messenger-dark-theme/blob/master/src/style.css).

That's what the scss file compiles down to and what's ultimately used in the extension.

**Comment by jerry1100** [comment]
Feel free to reopen if that doesn't work.

**Comment by wefalltomorrow** [comment]
> You can inject the [css file here](https://github.com/jerry1100/messenger-dark-theme/blob/master/src/style.css).
> 
> That's what the scss file compiles down to and what's ultimately used in the extension.

Wow that worked, I've never had any luck using CSS in Hamsket before but this works great. Thank you very much!
