### ISSUE TITLE
It does not work with Messenger sidebar app

### ISSUE THREAD

**Issue by Zuhasta** [jerry1100/messenger-dark-theme#27]
I wanted to use the black theme with sidebar messenger app but it looks like it doesn't work or am I doing something wrong? Appreciate your help in advance!

**Comment by jerry1100** [comment]
Are you referring to the messenger sidebar app in the Edge browser?

If so see #22

**Comment by Zuhasta** [comment]
Thank you, I see that it does not work with sidebar app.

**Comment by jerry1100** [comment]
Closing since this is a limitation in Edge
