### ISSUE TITLE
Messenger update killed readability

### ISSUE THREAD

**Issue by SoloMK** [jerry1100/messenger-dark-theme#28]
They updated something on messenger tonight, and the incoming chat's colors can no longer be read. It's a white background bubble with a very light grey looking text. The only way to read it with the dark theme on is to highlight it.

**Comment by dadanda** [comment]
if you can get the unpacked extension zip
add this to the style.css
--chat-incoming-message-bubble-background-color: #0f0f0f !important;
right after --warning: hsl(40, 89%, 52%) !important;
then load unpacked.

additional note: replies and some other text are using a different color which is under --wash
so if you want it to match use the same color as above.

**Comment by dadanda** [comment]
[messenger dark theme fix.zip](https://github.com/jerry1100/messenger-dark-theme/files/13112577/messenger.dark.theme.fix.zip)
Just unzip this (use extract here) then in load unpacked select the folder.
You should see manifest.json when you open the folder to be sure.
**NOTE: IF YOU MOVE THE FOLDER THE EXTENSION WILL BREAK AND YOU HAVE TO LOAD UNPACKED AGAIN.**

**Comment by Maxhou00** [comment]
@dadanda Why not creating a PR to fix the issue ?

**Comment by dadanda** [comment]
> @dadanda Why not creating a PR to fix the issue ?

https://github.com/jerry1100/messenger-dark-theme/pull/30
I didn't know how to do it till now, but here. Let's hope the owner can merge it and update it.

**Comment by jerry1100** [comment]
Thanks for raising this. Just submitted v1.8 which is undergoing approval, but should be published within the next 24 hrs on Chrome. Edge takes a while longer (about a week).

If you want it now, you can [download the zip here](https://github.com/jerry1100/messenger-dark-theme/files/13122985/messenger-dark-theme.zip). Then drag it into chrome://extensions/. Turn on the “Developer Mode” toggle if it’s not already on.

I'll leave this issue opened until it's approved & published on Chrome.

**Comment by ADTC** [comment]
Thank you! I came here to report exactly this.

**Comment by mikinty** [comment]
> Thanks for raising this. Just submitted v1.8 which is undergoing approval, but should be published within the next 24 hrs on Chrome. Edge takes a while longer (about a week).
> 
> If you want it now, you can download the zip from here: https://github.com/jerry1100/messenger-dark-theme/archive/refs/tags/v1.8.zip. Then drag it into chrome://extensions/.
> 
> I'll leave this issue opened until it's approved & published on Chrome.

Looks like the zip is missing the manifest? So it won't install in the extensions

**Comment by jerry1100** [comment]
> > Thanks for raising this. Just submitted v1.8 which is undergoing approval, but should be published within the next 24 hrs on Chrome. Edge takes a while longer (about a week).
> > If you want it now, you can download the zip from here: https://github.com/jerry1100/messenger-dark-theme/archive/refs/tags/v1.8.zip. Then drag it into chrome://extensions/.
> > I'll leave this issue opened until it's approved & published on Chrome.
> 
> Looks like the zip is missing the manifest? So it won't install in the extensions

You're right - I misinterpreted the releases artifacts. I updated my original comment with the correct zip.

**Comment by pogzie** [comment]
> Thanks for raising this. Just submitted v1.8 which is undergoing approval, but should be published within the next 24 hrs on Chrome. Edge takes a while longer (about a week).
> 
> If you want it now, you can [download the zip here](https://github.com/jerry1100/messenger-dark-theme/files/13122985/messenger-dark-theme.zip). Then drag it into chrome://extensions/.
> 
> I'll leave this issue opened until it's approved & published on Chrome.

To quickly add: you need to flip the "Developer Mode" switch on the upper right before dragging and dropping on the extensions page.

**Comment by ADTC** [comment]
> should be published within the next 24 hrs on Chrome

only 44 minutes left for "24 hrs" 😆 still not in the Chrome Web Store

**Comment by jerry1100** [comment]
> > should be published within the next 24 hrs on Chrome
> 
> only 44 minutes left for "24 hrs" 😆 still not in the Chrome Web Store

Yea, Google is taking longer than usual. I’ll leave this open until it’s updated.

**Comment by jerry1100** [comment]
Update: it got rejected, likely because the tester failed to log in. Submitted an appeal and resubmitted for publishing, so hopefully it gets approved this time.

<img width="493" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/18181641/4119d50a-d762-4cfa-acb4-96eb0a0880bb">

**Comment by griffinwebnet** [comment]
Glad to see this is in the works. i tried to fix with stylus but the var seems procedurally injected by whatever js framework theyre using on MVC Route change so even if i can get the bubbles to change, the next conversation i click on theyre back to unreadable so i'm glad to see theres something in the works. Sorry to hear about the google approval team. I swear sometimes the testers are great, sometimes they cant seem to rub 2 braincells together. The number of rounds I've had to go with them because their "testers" are actually just incompetent is unreal.

**Comment by ADTC** [comment]
It's finally out. Just updated, and it's working well. Thank you. I think this can be closed now.

**Comment by jerry1100** [comment]
Thanks for the updates, closing as resolved.

**Comment by Pizzachu61** [comment]
thank you for the update!
