### ISSUE TITLE
white text boxes

### ISSUE THREAD

**Issue by chocomint16** [jerry1100/messenger-dark-theme#29]
i can't read the messages because text boxes are white after i added this extension. This only applies to the replies of the person im talking to.

**Comment by tamaskovacsliferay** [comment]
Same issue as #28

**Comment by numzie** [comment]
Same here. Started today and seems to be a change in Chrome as other extensions doing the same has the same issue.
Screenshot:

![image](https://github.com/jerry1100/messenger-dark-theme/assets/15649255/9292fc9b-a759-4c58-83f9-62bf90e9cbd2)

**Comment by vindvd** [comment]
Chat doesn't change to white when it is a reply to a message though.

**Comment by jerry1100** [comment]
Thanks for raising this. Just submitted v1.8 which is undergoing approval, but should be published within the next 24 hrs on Chrome. Edge takes a while longer (about a week).

If you want it now, you can download the zip from here: https://github.com/jerry1100/messenger-dark-theme/archive/refs/tags/v1.8.zip. Then drag it into chrome://extensions/.

I'll leave this issue opened until it's approved & published on Chrome.

Let's move the discussion to #28.
