### ISSUE TITLE
Make Sidebar Text Less White

### ISSUE THREAD

**Issue by tvut** [jerry1100/messenger-dark-theme#3]
The text in the sidebar is really white. In the windows desktop client if the message has already been seen then the text turns a lighter grey (something like #CCC) which makes it easier to look at.

**Comment by jerry1100** [comment]
Thanks @tvut for reporting. I agree #FFF is a bit harsh, but #CCC is a bit too dark. I settled on #ECECEC.

Just submitted v0.7, will probably take a few days to get approved & published.
