### ISSUE TITLE
White message background

### ISSUE THREAD

**Issue by Ingnition** [jerry1100/messenger-dark-theme#32]
Hello. The plugin is currently not working properly. Shows a white background in messages from friends. Is it possible to fix it? I love this extension and would love to continue using it. Thank you very much! :)
![white_messages](https://github.com/jerry1100/messenger-dark-theme/assets/4060547/1cafd1b1-2cac-4111-b61a-a47105539ba1)

**Comment by jerry1100** [comment]
Hi, this has been fixed. If you’re on edge, see https://github.com/jerry1100/messenger-dark-theme/issues/31#issuecomment-1782510633.

If you’re in chrome, go to chrome://extensions and press “Update”.

Closing but feel free to reopen if that’s not working for you.

**Comment by Ingnition** [comment]
I use your extension in Edge browser. Is it possible to update it here as well? I normally use Chrome, but specifically on Messenger I have it open separately in Edge. Thank you very much! :)

**Comment by jerry1100** [comment]
I already submitted an update, but Microsoft just takes a while to approve it. :/

**Comment by jerry1100** [comment]
You can use chrome extensions on edge if you want the fix now. See the link in my comment above for instructions.

**Comment by Ingnition** [comment]
I understand. Thank you very much :) I solved it with your advice about Chrome extension to Edge.
