### ISSUE TITLE
Black icons

### ISSUE THREAD

**Issue by ADTC** [jerry1100/messenger-dark-theme#34]
<img width="417" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/4d24b9ed-d605-4109-b87f-af90f2f64700">

<img width="382" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/4280d386-31c3-43a6-ae64-e4602772032b">

**Comment by ADTC** [comment]
I hope you're okay. Haven't seen any recent activity from you.

**Comment by jerry1100** [comment]
Oops sorry I missed this. Am on vacation. I’ll find some time to take a look at it this week or the next.

**Comment by jerry1100** [comment]
Reporting back: I'll take a look at it first week of January. Pretty busy enjoying my vacation for the rest of the year :).

**Comment by ADTC** [comment]
No worries. Happy Holidays!

**Comment by jerry1100** [comment]
Just submitted v1.9 in both chrome and edge stores which fixes this. Should be out within the next few days, I'll leave this issue open until it's out.

**Comment by jerry1100** [comment]
[v1.9](https://chromewebstore.google.com/detail/messenger-dark-theme/eobhfnijalkolbbmdoonheekjidkoojd) is released on Chrome.

Closing this as it's resolved. Thanks for reporting.

**Comment by ADTC** [comment]
OK seriously, Google, how on Earth do I update this? My extension manager shows 1.8 and the Chrome Web Store shows 1.9 but NEITHER is showing an Update button or automatically updating. SO FRUSTRATING.

@jerry1100 thanks for the fix though.

**Comment by ADTC** [comment]
Apparently I have to enable "Developer Mode" then click on the "Update" button that appears. No idea why it's hidden there.
