### ISSUE TITLE
Message Area is color white

### ISSUE THREAD

**Issue by Virus5600** [jerry1100/messenger-dark-theme#35]
Similar to before, messenger probably updated again resulting to the extension not working properly and leaving the chat area background color white.

The area in question is this:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/19548426/dd4b89a1-4ae1-43e1-8ad7-d680a4b625fb)

The class in question:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/19548426/6e7928fa-1736-4039-8e15-9ca4f9d9f3d7)

The variable came from here:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/19548426/fc7cd213-1133-4e19-81d6-09cc119c7f2a)

**Comment by jerry1100** [comment]
Just submitted [v1.10](https://chromewebstore.google.com/detail/messenger-dark-theme/eobhfnijalkolbbmdoonheekjidkoojd) which fixes this, which should get published soon.

I'll leave this open until it gets published. Thanks for reporting.

**Comment by Feriman22** [comment]
Works as expected, thanks a lot for quick fix!
I had to uninstall and reinstall the addon (I don't know how to force an addon update in Chrome).

**Comment by Virus5600** [comment]
Definitely worked. Thanks for the update!

**Comment by ADTC** [comment]
@Feriman22 enable the Developer mode checkbox. You'll see the Update button. Click on it to update.

Don't ask me why the Update button is inside developer mode. It tripped me up too.
