### ISSUE TITLE
Scrollbars stay white  (Chrome v120 + Win11 & MacOS)

### ISSUE THREAD

**Issue by ndave92** [jerry1100/messenger-dark-theme#36]
The scrollbars look like this on both Win11 and MacOS:
![messenger](https://github.com/jerry1100/messenger-dark-theme/assets/11756416/009a4d60-a352-4772-9e30-4ec5c8df462a)

The system and browser themes are also set to dark on both systems.
I also checked other websites with built-in dark mode and the scrollbars are dark everywhere, but here.
I added this line to :root and it seems to fix the issue:
`:root {
  color-scheme: dark;
}`

![code](https://github.com/jerry1100/messenger-dark-theme/assets/11756416/8ea40084-3c62-4514-a6dc-b4dfe62db016)

![messenger_fixed](https://github.com/jerry1100/messenger-dark-theme/assets/11756416/98e19f62-dd7a-49d3-8eec-c3182a5d4318)

Can you please fix this?
Thanks in advance!

**Comment by jerry1100** [comment]
Submitted [v1.11](https://chromewebstore.google.com/detail/messenger-dark-theme/eobhfnijalkolbbmdoonheekjidkoojd) for review, should be published soon.

Leaving this open until it's published. Thanks for reporting.

**Comment by jerry1100** [comment]
v1.11 is out on Chrome, so closing this.
