### ISSUE TITLE
Chat window background is white

### ISSUE THREAD

**Issue by motleyDevil** [jerry1100/messenger-dark-theme#37]
![image](https://github.com/jerry1100/messenger-dark-theme/assets/151942244/86e12a65-8551-4e57-807b-df81346a4fcd)

**Comment by jerry1100** [comment]
Hi, please update your extension to v1.10. You can do so by going to chrome://extensions and uninstalling then reinstalling.

See https://github.com/jerry1100/messenger-dark-theme/issues/35#issuecomment-1888568819

**Comment by motleyDevil** [comment]
Sorry for the lack of detail on the ticket. I'm using Edge, not Chrome.

I tried grabbing latest from the Edge store but it's 1.9 so it looks like
perhaps it hasn't been posted yet?

**Comment by jerry1100** [comment]
I see. Yeah I submitted a new version but it hasn't been approved yet. The edge store usually takes a week to approve and publish it.

In the meantime you can try [installing chrome extensions from edge](https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026).

**Comment by motleyDevil** [comment]
Thanks for the reply and the quick work.
