### ISSUE TITLE
Main message window is now mostly white.

### ISSUE THREAD

**Issue by casmer** [jerry1100/messenger-dark-theme#38]
Open the browser on edge today and the background on the message area is suddenly white.
![image](https://github.com/jerry1100/messenger-dark-theme/assets/6509468/4c6f475d-2d2c-475a-8950-1130d7435c31)

**Comment by jerry1100** [comment]
Hi, please see https://github.com/jerry1100/messenger-dark-theme/issues/37#issuecomment-1889628302
