### ISSUE TITLE
⚠️⚠️‼️ EMERGENCY: White background in chat

### ISSUE THREAD

**Issue by ADTC** [jerry1100/messenger-dark-theme#39]
See below. Just started today.

<img width="496" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/770c29f9-78be-48b5-88fa-06d115f35376">

**Comment by ADTC** [comment]
Oh never mind. I had to update Google Chrome to Version 120.0.6099.216 (Official Build) (arm64) and it is now fixed... Weird!

**Comment by jerry1100** [comment]
Actually, it’s because of https://github.com/jerry1100/messenger-dark-theme/issues/35. Your extension probably just updated when you updated chrome.

**Comment by ADTC** [comment]
That's probably it. Thank you!
