### ISSUE TITLE
Follow System Dark Mode Settings

### ISSUE THREAD

**Issue by tvut** [jerry1100/messenger-dark-theme#4]
It would be nice if the plugin followed the system dark mode settings so when your system is in light mode messenger would be in light mode and if your system is in dark mode then messenger would be in dark mode. (You could do this with media queries.)

**Comment by jerry1100** [comment]
Thanks @tvut for the suggestion.

I don't think we should follow the system theme since that would mean forcing users to use the system dark mode if they want to use the messenger dark mode, which isn't ideal.

Currently, if they want messenger light mode, they can just disable the extension. Albeit a little inconvenient, it offers the most flexibility.

**Comment by NomarCub** [comment]
Could this functionality be provided optionally? A little toggleable setting for those who want it.
I want every site to follow dark mode and not have to switch them individually. I use [Windows Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) and [Dark Reader](https://github.com/darkreader/darkreader), but many sites have native auto dark mode now.

**Comment by jerry1100** [comment]
Unfortunately I don't have time to build this out. I also don't see the benefit of this, besides for users who alternative between light & dark modes frequently. I feel the majority of users are satisfied with the always dark mode.

>I want every site to follow dark mode and not have to switch them individually.

The extension in its current form makes messenger dark, so I'm not sure what you mean by having to switch every site individually.

**Comment by NomarCub** [comment]
My PC switches from dark to light mode and back at sunset and sundown, automatically. Apps on my PC are affected, as are all websites through native support or Dark Reader. I switch frequently, but not manually. That's the benefit.

I don't think it would take much time. But I understand if you don't have the time.
