### ISSUE TITLE
Call buttons changed to white

### ISSUE THREAD

**Issue by maxoku** [jerry1100/messenger-dark-theme#40]
Call buttons that are above the chat for making voice and video calls changed to white. They should be blue like the 3 dots button.
![image](https://github.com/jerry1100/messenger-dark-theme/assets/17256400/4f6445d9-a00a-46bb-ac92-319edbaa7eca)

Without the dark style they are blue.
![image](https://github.com/jerry1100/messenger-dark-theme/assets/17256400/da1878bf-ff03-4788-b14b-1723289c2b1c)

Could you fix that it would be blue?

**Comment by ndave92** [comment]
Actually, the three-dot button should be white, not the other way around.

**Comment by maxoku** [comment]
> Actually, the three-dot button should be white, not the other way around.

What for? They are originally blue, so they should stay blue. If they were black then they should be white.

**Comment by ndave92** [comment]
Okay, I just checked it without the extension and all three buttons up there follow the chat's theme color (e.g. it can also be red, green, etc., not only blue), so it should behave the same way with the extension enabled.

**Comment by jerry1100** [comment]
Just submitted v1.12 which fixes this, should arrive in a few days.

<img width="135" alt="Screenshot 2024-02-16 at 9 27 28 PM" src="https://github.com/jerry1100/messenger-dark-theme/assets/18181641/f323b7ca-53f5-4567-b9fe-9e52468e0233">

**Comment by jerry1100** [comment]
v12 is live on Chrome! Closing this out.
