### ISSUE TITLE
Selected and hovered contacts not noticeable

### ISSUE THREAD

**Issue by maxoku** [jerry1100/messenger-dark-theme#41]
When a chat is selected or hovered their background color is almost the same as the general background color. So I can't see which chat is selected.
![image](https://github.com/jerry1100/messenger-dark-theme/assets/17256400/0aa057f4-dda7-43d2-8693-ee8e8be8498a)

When I click on a chat for a moment (of clicking) there is a different color)
![image](https://github.com/jerry1100/messenger-dark-theme/assets/17256400/ad230e03-f79a-4059-8906-5ff38c87043e)

That color should be also when a chat is selected and hovered or even 3 different (but noticeable) colors for every state.

**Comment by jerry1100** [comment]
Thanks for reporting. Just submitted v1.12 which fixes this.

Selected state:
<img width="362" alt="Screenshot 2024-02-16 at 7 58 31 PM" src="https://github.com/jerry1100/messenger-dark-theme/assets/18181641/92d847c2-5dfa-4695-a1a4-46f104171b06">

Hover state:
<img width="366" alt="Screenshot 2024-02-16 at 7 58 25 PM" src="https://github.com/jerry1100/messenger-dark-theme/assets/18181641/6c35b112-cb2c-4b81-ad1d-fb9cda23b521">

**Comment by jerry1100** [comment]
v12 is live on Chrome! Closing this out.
