### ISSUE TITLE
Non-reply sent messages in themed chats have the standard blue color instead of theme color

### ISSUE THREAD

**Issue by ADTC** [jerry1100/messenger-dark-theme#42]
I have a chat that has an orange theme. In the mobile app, the sent messages are themed in an orange gradient (gets lighter as it moves upward).

In messenger.com with your extension, the non-reply sent messages get a standard blue color while the reply-style sent messages get the orange theme. The Like symbol also gets the orange theme.

<img width="269" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/00b60998-7fc6-4794-bca2-7cf64082d902">
<img width="210" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/5df6e045-8db2-4426-8ca9-80efce5d1a8a">

Expectation: all sent messages follow the theme.

**Comment by jerry1100** [comment]
Ah I must’ve broken this with the latest update. I’ll take a look today.

**Comment by jerry1100** [comment]
Submitted v1.13 with the fix - should be published on Chrome soon. Thanks for reporting.

**Comment by ADTC** [comment]
Thanks! Fixed in 1a974d23d2f49867183fed8e37cb624b77ad898b.
