### ISSUE TITLE
Adding options of other shades of darkness? 😎

### ISSUE THREAD

**Issue by DdariQ** [jerry1100/messenger-dark-theme#43]
Hi, your extension compared to the other dark mode extension called Charcoal seems better at a quick comparison glance, especially, how the buttons (f.e. reply, react) are visible, and the scroll bars are also dark, among other quality of life stuff. Simply, yours is the better extension.

But Charcoal is darker, it's closer to the OLED full black - I believe it's called something like this. I don't know anything about development, I'm just a casual user, but would you be able to add darker shades of blacks we could choose from? I prefer a darker shade of gray, or even almost fully black compared to your lighter gray.

**Comment by jerry1100** [comment]
Hey @DdariQ, I agree it would be cool to provide more color options, especially darker ones. However, that's not something I can realistically add and continue to maintain given the amount of time I'm willing to spend on this.

Hope you understand!
