### ISSUE TITLE
Official "Dark Mode" has arrived!

### ISSUE THREAD

**Issue by ADTC** [jerry1100/messenger-dark-theme#44]
I noticed that [messenger.com](https://www.messenger.com/) has a new look (though I don't really like it because they added so much dead space around each of the panels, and there's also a dead scrollbar on the right edge).

And I looked in the Preferences pane and noticed this:

<img width="557" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/f46b285d-f757-47dc-a56a-098c7498ab44">

I disabled the extension, and the official Dark Mode works well. I guess I may not need this extension anymore, although if you'd write another one to fix the dead space and dead scrollbar, I'd be all over it.

Please keep this repo and extension though, as I don't know if everyone has this update already or not. Could be a limited beta or something.

**Comment by jerry1100** [comment]
I'm not seeing this preference - maybe I don't have the update yet.

Did you find it here?

<img width="346" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/18181641/d107295d-a027-40c6-aa5f-be8d912bb34a">

**Comment by ADTC** [comment]
Yes in Preferences. Have you tried a cache refresh? Does your UI look different generally though?

**Comment by ADTC** [comment]
The UI has a lot of bezel spacing now between panels (I dislike this.) and there's also a dead scrollbar on the viewport's right edge.

<img width="1105" alt="image" src="https://github.com/jerry1100/messenger-dark-theme/assets/6047296/f994526a-acf4-442e-9032-c47bc8f30dd1">


IDK if you need to migrate to the new End-to-end encryption rolled out recently, coincidentally with this change as well. The URL of the page starts with `https://www.messenger.com/e2ee/` where the `e2ee` probably stands for end-to-end encrypted.

**Comment by jerry1100** [comment]
Interesting. My UI still looks the same and disabling cache didn't do anything, so I'm guessing it's still being rolled out.

I'll keep an eye out, thanks for the info.

**Comment by Nagidrop** [comment]
The feature was rolling out. It hit me yesterday, but some people already had it, and news also came way earlier. 

I wonder how @jerry1100 decide the fate of this project? Are there any plans for archiving or adding color customization in the future? :D

**Comment by jerry1100** [comment]
I see the native version now and it looks really good. I decided I'm going to deprecate this extension since it's not necessary anymore ([see README](https://github.com/jerry1100/messenger-dark-theme?tab=readme-ov-file#messenger-dark-theme-deprecated)).

I'll leave it up until the end of July in case it's not rolled out everywhere yet, but I'll unpublish it from the stores afterwards so users won't have to rely on a 3rd party solution when a good 1st party one exists.

Thanks for all the feedback on this.
