### ISSUE TITLE
White Circles Around the Chat Heads

### ISSUE THREAD

**Issue by tvut** [jerry1100/messenger-dark-theme#5]
![image](https://user-images.githubusercontent.com/63570267/98069394-a294ff00-1e2c-11eb-86eb-1130898e2f02.png)
Is there any way to remove or change the color of these circles for profile pics for groups?

**Comment by jerry1100** [comment]
Hey, thanks for reporting and submitting a PR. Will take a look this weekend

**Comment by jerry1100** [comment]
Thanks @tvut for the suggestion.

I removed the border and made the images a big bigger to fill in the extra space.
![Screen Shot 2020-11-08 at 4 18 58 PM](https://user-images.githubusercontent.com/18181641/98493262-1d1f9f00-21de-11eb-8b19-4c53dbc6c8f6.png)

Just submitted v0.7, should see it later this week.
