### ISSUE TITLE
Error installing via MS edge store

### ISSUE THREAD

**Issue by kristod1** [jerry1100/messenger-dark-theme#9]
When you try and install the package via the Microsoft edge store it returns an error sayin "Package is invalid. Details: "Couldn't load icon icons/icon16.png specified in icons."

**Comment by jerry1100** [comment]
Hey, thanks for letting me know.

I submitted a new version, it should go live within 1-2 days. Please look for v0.8.


Jerry

**Comment by jerry1100** [comment]
Closing since it should be resolved. If it's not, feel free to reopen.
